"""initial_schema

Revision ID: 56868d7224b4
Revises: 
Create Date: 2026-04-27 20:15:47.942274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56868d7224b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trading_name', sa.String(length=255), nullable=True),
    sa.Column('company_type', sa.Enum('PRIVATE_LIMITED', 'PUBLIC_LIMITED', 'PARTNERSHIP', 'SOLE_TRADER', 'CLUB_ASSOCIATION', 'NGO', 'GOVERNMENT', 'OTHER', name='companytype'), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('registration_year', sa.String(length=10), nullable=True),
    sa.Column('date_of_formation', sa.DateTime(), nullable=True),
    sa.Column('vat_number', sa.String(length=50), nullable=True),
    sa.Column('tin_number', sa.String(length=50), nullable=True),
    sa.Column('registration_town', sa.String(length=100), nullable=True),
    sa.Column('business_sector', sa.String(length=100), nullable=True),
    sa.Column('goods_services', sa.Text(), nullable=True),
    sa.Column('insurer', sa.String(length=100), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('gross_annual_revenue', sa.Float(), nullable=True),
    sa.Column('total_expenses', sa.Float(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('credit_score_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_name', 'companies', ['name'], unique=False)
    op.create_index('ix_companies_reg_no', 'companies', ['registration_number'], unique=False)
    op.create_index(op.f('ix_companies_registration_number'), 'companies', ['registration_number'], unique=False)
    op.create_table('individuals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('drivers_licence', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'UNSPECIFIED', name='maritalstatus'), nullable=False),
    sa.Column('is_foreigner', sa.Boolean(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('credit_score_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_individuals_name', 'individuals', ['last_name', 'first_name'], unique=False)
    op.create_index(op.f('ix_individuals_national_id'), 'individuals', ['national_id'], unique=False)
    op.create_index('ix_individuals_passport', 'individuals', ['passport_number'], unique=False)
    op.create_index(op.f('ix_individuals_passport_number'), 'individuals', ['passport_number'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trading_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING', 'INACTIVE', name='subscriberstatus'), nullable=False),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('max_searches_per_month', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('company_addresses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('street_no', sa.String(length=50), nullable=True),
    sa.Column('street_name', sa.String(length=200), nullable=False),
    sa.Column('suburb', sa.String(length=100), nullable=True),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('po_box', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('property_density', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='propertydensity'), nullable=True),
    sa.Column('property_ownership', sa.Enum('OWNED', 'RENTED', 'MORTGAGED', 'OTHER', name='propertyownership'), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('directors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('individual_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'UNSPECIFIED', name='maritalstatus'), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PROCESSING', 'GOOD', 'GREEN', 'ADVERSE', 'PEP', 'FAIR', 'INCONCLUSIVE', 'REJECTED', 'CONFIRMATION', 'CONFIRMED', 'INCOMPLETE', name='searchstatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('individual_addresses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('individual_id', sa.String(), nullable=False),
    sa.Column('street_no', sa.String(length=50), nullable=True),
    sa.Column('street_name', sa.String(length=200), nullable=False),
    sa.Column('suburb', sa.String(length=100), nullable=True),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('po_box', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('property_density', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='propertydensity'), nullable=True),
    sa.Column('property_ownership', sa.Enum('OWNED', 'RENTED', 'MORTGAGED', 'OTHER', name='propertyownership'), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('individual_employment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('individual_id', sa.String(), nullable=False),
    sa.Column('employer', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('salary_band_usd', sa.String(length=50), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subscriber_id', sa.String(), nullable=False),
    sa.Column('individual_id', sa.String(), nullable=True),
    sa.Column('loan_reference', sa.String(length=100), nullable=True),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('outstanding_balance', sa.Float(), nullable=True),
    sa.Column('loan_purpose', sa.String(length=100), nullable=True),
    sa.Column('loan_start_date', sa.DateTime(), nullable=True),
    sa.Column('loan_end_date', sa.DateTime(), nullable=True),
    sa.Column('installment_amount', sa.Float(), nullable=True),
    sa.Column('installment_frequency', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PERFORMING', 'DELINQUENT', 'DEFAULT', 'WRITTEN_OFF', 'SETTLED', 'RESTRUCTURED', name='loanstatus'), nullable=False),
    sa.Column('days_in_arrears', sa.Integer(), nullable=True),
    sa.Column('times_defaulted', sa.Integer(), nullable=True),
    sa.Column('date_of_default', sa.DateTime(), nullable=True),
    sa.Column('date_settled', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loan_records_individual', 'loan_records', ['individual_id'], unique=False)
    op.create_index('ix_loan_records_status', 'loan_records', ['status'], unique=False)
    op.create_index('ix_loan_records_subscriber', 'loan_records', ['subscriber_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subscriber_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'SUBSCRIBER', 'READ_ONLY', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('company_searches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('search_ref', sa.String(length=20), nullable=False),
    sa.Column('subscriber_id', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('search_purpose', sa.Enum('NEW_CUSTOMER_KYC', 'EXISTING_CUSTOMER', 'PERIODIC_ACCOUNT_REVIEW', 'CREDIT_APPLICATION', 'EMPLOYMENT_VETTING', 'TENANT_VETTING', 'BUSINESS_PARTNER', 'OTHER', name='searchpurpose'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PROCESSING', 'GOOD', 'GREEN', 'ADVERSE', 'PEP', 'FAIR', 'INCONCLUSIVE', 'REJECTED', 'CONFIRMATION', 'CONFIRMED', 'INCOMPLETE', name='searchstatus'), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('loan_purpose', sa.String(length=100), nullable=True),
    sa.Column('loan_amount', sa.Float(), nullable=True),
    sa.Column('processed_by_id', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Enum('INCORRECT_ID', 'DUPLICATE_ID', 'INCORRECT_ADDRESS', 'MULTIPLE_IDS', 'NOT_ENOUGH_DIRECTORS', 'MISSING_REG_NO', 'OTHER', name='rejectionreason'), nullable=True),
    sa.Column('rejection_comments', sa.Text(), nullable=True),
    sa.Column('confirmation_reason', sa.Text(), nullable=True),
    sa.Column('confirmation_response', sa.Text(), nullable=True),
    sa.Column('report_generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_ref')
    )
    op.create_index('ix_com_searches_ref', 'company_searches', ['search_ref'], unique=False)
    op.create_index('ix_com_searches_status', 'company_searches', ['status'], unique=False)
    op.create_index('ix_com_searches_subscriber', 'company_searches', ['subscriber_id'], unique=False)
    op.create_table('individual_searches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('search_ref', sa.String(length=20), nullable=False),
    sa.Column('subscriber_id', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('individual_id', sa.String(), nullable=True),
    sa.Column('search_purpose', sa.Enum('NEW_CUSTOMER_KYC', 'EXISTING_CUSTOMER', 'PERIODIC_ACCOUNT_REVIEW', 'CREDIT_APPLICATION', 'EMPLOYMENT_VETTING', 'TENANT_VETTING', 'BUSINESS_PARTNER', 'OTHER', name='searchpurpose'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PROCESSING', 'GOOD', 'GREEN', 'ADVERSE', 'PEP', 'FAIR', 'INCONCLUSIVE', 'REJECTED', 'CONFIRMATION', 'CONFIRMED', 'INCOMPLETE', name='searchstatus'), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('loan_purpose', sa.String(length=100), nullable=True),
    sa.Column('loan_amount', sa.Float(), nullable=True),
    sa.Column('processed_by_id', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Enum('INCORRECT_ID', 'DUPLICATE_ID', 'INCORRECT_ADDRESS', 'MULTIPLE_IDS', 'NOT_ENOUGH_DIRECTORS', 'MISSING_REG_NO', 'OTHER', name='rejectionreason'), nullable=True),
    sa.Column('rejection_comments', sa.Text(), nullable=True),
    sa.Column('confirmation_reason', sa.Text(), nullable=True),
    sa.Column('confirmation_response', sa.Text(), nullable=True),
    sa.Column('report_generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_ref')
    )
    op.create_index('ix_ind_searches_ref', 'individual_searches', ['search_ref'], unique=False)
    op.create_index('ix_ind_searches_status', 'individual_searches', ['status'], unique=False)
    op.create_index('ix_ind_searches_subscriber', 'individual_searches', ['subscriber_id'], unique=False)
    op.create_table('shareholders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('director_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shareholding_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['director_id'], ['directors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shareholders')
    op.drop_index('ix_ind_searches_subscriber', table_name='individual_searches')
    op.drop_index('ix_ind_searches_status', table_name='individual_searches')
    op.drop_index('ix_ind_searches_ref', table_name='individual_searches')
    op.drop_table('individual_searches')
    op.drop_index('ix_com_searches_subscriber', table_name='company_searches')
    op.drop_index('ix_com_searches_status', table_name='company_searches')
    op.drop_index('ix_com_searches_ref', table_name='company_searches')
    op.drop_table('company_searches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_loan_records_subscriber', table_name='loan_records')
    op.drop_index('ix_loan_records_status', table_name='loan_records')
    op.drop_index('ix_loan_records_individual', table_name='loan_records')
    op.drop_table('loan_records')
    op.drop_table('individual_employment')
    op.drop_table('individual_addresses')
    op.drop_table('directors')
    op.drop_table('company_addresses')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_individuals_passport_number'), table_name='individuals')
    op.drop_index('ix_individuals_passport', table_name='individuals')
    op.drop_index(op.f('ix_individuals_national_id'), table_name='individuals')
    op.drop_index('ix_individuals_name', table_name='individuals')
    op.drop_table('individuals')
    op.drop_index(op.f('ix_companies_registration_number'), table_name='companies')
    op.drop_index('ix_companies_reg_no', table_name='companies')
    op.drop_index('ix_companies_name', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
